//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GBBD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shtraf
    {
        public int Id { get; set; }
        public int CarId { get; set; }
        public Nullable<int> Region { get; set; }
        public string LicenceNum { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public byte[] Photo { get; set; }
        public Nullable<int> StatusId { get; set; }
    
        public virtual Car Car { get; set; }
        public virtual Status Status { get; set; }
    }
}
